### ISSUE TITLE
Ошибка при использовании конфига через eslint-loader

### ISSUE THREAD

**Issue by Yuricoden** [doasync/eslint-config-airbnb-standard#1]
После установки просило установить все пакеты с bundleDependencies пришлось все накатывать к себе в сборку только после этого loader запустился

![image](https://user-images.githubusercontent.com/19597527/34051551-b2bd773a-e1c7-11e7-9fde-3e82b70cc7ab.png)

![image](https://user-images.githubusercontent.com/19597527/34051570-c2c71820-e1c7-11e7-81fd-bb0abd2d53da.png)

**Comment by doasync** [comment]
Привет! Спасибо за feedback. Добавил в readme заметку про использование внутреннего `eslint`.

Добавлять `eslint` в список зависимостей не требуется. Он уже есть в этом пакете (со всеми необходимыми плагинами), нужно лишь прописать путь для `eslint-loader`:
```
{
  loader: 'eslint-loader',
  options: {
    eslintPath: 'eslint-config-airbnb-standard/node_modules/eslint',
  }
},
```
