### ISSUE TITLE
VSCode Windows Error: Failed to load plugin: Cannot find module 'eslint-plugin-import'

### ISSUE THREAD

**Issue by jmbothe** [doasync/eslint-config-airbnb-standard#2]
When using `eslint-config-airbnb-standard` in Visual Studio Code on Windows 10, I get this error from VSCode:

`Error: Failed to load plugin: Cannot find module 'eslint-plugin-import'

So here is the problem as I see it: `eslint-config-airbnb-standard` installs its own dependencies in its own `node_modules` directory deep in the projects main `node_modules` directory. Windows has a limit on on the maximum number of characters allowed in a file path: 260 characters. So the end result is that the dependencies of `"eslint-config-airbnb-standard` are unreachable by the VSCode ESLint plugin, and you get the error.

I went to the command line and manually `npm install`'d that dependency, so as to get another copy in a shallower directory that is reachable by VSCode, but the problem is there are actually MANY dependencies that are unreachable, so once I installed that dependency, I just get a new error for the next unreachable dependency. There were like seven or eight in all, I think...

The best thing I found to do is to run [`npm dedupe`](https://docs.npmjs.com/cli/dedupe). This lovely little command will flatten out your `node_modules` directory, making all of those dependencies accessible to VSCode.

I don't know a whole lot about developing npm packages, but is this something y'all should fix, or should I make this an issue with node, or npm, or VSCode? Or Microsoft??? hahahah.

**Comment by moltar** [comment]
Have the same problem on macOS too.

**Comment by doasync** [comment]
I've updated README with VSCode instructions. Update the package to v2.1.5 if you have any troubles.
